baseURL: 'https://mayukhdeb.github.io/blog/'
languageCode: en-us
title: '@mayukhdeb'
baseurl: ''
theme: hugo-PaperMod
min_version: 0.57.0
contentdir: content
layoutdir: layouts
builddrafts: True
canonifyurls: False
publishDir: docs
params:
    homeInfoParams:
        Title: Hi, I'm Mayukh
        Content: I spend most of my time messing with deep-learning models and trying to reverse engineer them (which eventually led to [torch-dreams](https://github.com/Mayukhdeb/torch-dreams), my favourite personal project). <br>  Apart from that I also work with [INCF](https://incf.org/)/[OpenWorm](http://openworm.org/) to build a [toolkit](https://github.com/DevoLearn/devolearn) to help accelerate research in data driven developmental biology. Welcome to this corner of the internet.
    params:
    defaultTheme: dark
taxonomies:
  tag: tags
menu:
  top:
    - name: Github
      pre: ''
      weight: 1
      url: 'https://github.com/Mayukhdeb'
    - name: Twitter
      pre: ''
      weight: 1
      url: 'https://twitter.com/mayukh091'
      

